# Generated by Django 4.0.2 on 2022-02-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tag',
            field=models.ManyToManyField(blank=True, to='invoices.Tag'),
        ),
    ]
