# Generated by Django 4.0.2 on 2022-02-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_rename_tag_invoice_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tags',
        ),
    ]
